function action = baselineFixedPacket(~, ~) %#ok<INUSD>
%BASELINEFIXEDPACKET Fixed-packet-size transmission (no adaptation).
%   Mid-sized 80-byte packet with moderate repetition (R = 4), QPSK and
%   TTI = 4 ms. Represents a conservative one-size-fits-all configuration
%   commonly used in field deployments where channel state is unknown.

action = struct( ...
    'packet',      80, ...
    'rep',          4, ...
    'mod',     "QPSK", ...
    'tti',          4, ...
    'name', "FixedPacket");
end
