function action = baselineConventional(~, ~) %#ok<INUSD>
%BASELINECONVENTIONAL Conventional NB-IoT (no adaptation).
%   3GPP Release 13 default settings used in commercial NB-IoT deployments:
%   125-byte transport block, no repetitions, QPSK modulation, 1 ms TTI.
%   Provides the baseline against which adaptive schemes are compared.

action = struct( ...
    'packet',     125, ...
    'rep',          1, ...
    'mod',     "QPSK", ...
    'tti',          1, ...
    'name', "Conventional");
end
